name: Deploy AI Interview System

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  # Use GitHub Secrets for secure API key management
  VITE_OPENROUTER_API_KEY: ${{ secrets.VITE_OPENROUTER_API_KEY }}
  VITE_OPENROUTER_MODEL: ${{ secrets.VITE_OPENROUTER_MODEL }}
  VITE_GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.VITE_GOOGLE_CLOUD_PROJECT_ID }}
  VITE_DOCUMENT_AI_PROCESSOR_ID: ${{ secrets.VITE_DOCUMENT_AI_PROCESSOR_ID }}
  VITE_DOCUMENT_AI_LOCATION: ${{ secrets.VITE_DOCUMENT_AI_LOCATION }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Build application
      run: npm run build
      env:
        # Ensure environment variables are available during build
        VITE_OPENROUTER_API_KEY: ${{ secrets.VITE_OPENROUTER_API_KEY }}
        VITE_OPENROUTER_MODEL: ${{ secrets.VITE_OPENROUTER_MODEL }}
        VITE_GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.VITE_GOOGLE_CLOUD_PROJECT_ID }}
        VITE_DOCUMENT_AI_PROCESSOR_ID: ${{ secrets.VITE_DOCUMENT_AI_PROCESSOR_ID }}
        VITE_DOCUMENT_AI_LOCATION: ${{ secrets.VITE_DOCUMENT_AI_LOCATION }}

    - name: Preview build (development only)
      if: github.event_name == 'pull_request'
      run: npm run preview &

    # Uncomment and configure for your hosting platform
    # Example for Vercel deployment:
    # - name: Deploy to Vercel
    #   if: github.ref == 'refs/heads/main'
    #   uses: vercel/action@v1
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}

    # Example for Netlify deployment:
    # - name: Deploy to Netlify
    #   if: github.ref == 'refs/heads/main'
    #   uses: nwtgck/actions-netlify@v3.0
    #   with:
    #     publish-dir: './dist'
    #     production-deploy: true
    #   env:
    #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    # Example for GitHub Pages deployment:
    # - name: Deploy to GitHub Pages
    #   if: github.ref == 'refs/heads/main'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist